### ISSUE TITLE
Is it supports Yandex.Connect?

### ISSUE THREAD

**Issue by misha-plus** [thekvs/yandex-ddns#1]
Hello. Do you know is this utility supports new Yandex.Connect service.

**Comment by thekvs** [comment]
Hi!

Does it have different API for managing DNS records? I've looked through https://yandex.ru/support/connect/domains.html and didn't find any mentions of an external API.

**Comment by misha-plus** [comment]
Thank you.
It seems like they don't have API for Connect right now. Hope that Yandex will add this in the future.
https://toster.ru/q/544909

**Comment by thekvs** [comment]
Now it supports new Yandex.Connect DNS API.
